version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: qrcode_server_1
      APP_PORT: 4867
    
  server:
    image: giandonatoinverso/php-dynamic-qr-code-db:latest
    user: "1000:1000"
    init: true
