version: "3.7"

services:
  php-dynamic-qrcode:
    image: "giandonatoinverso/php-dynamic-qr-code:latest"
    restart: "unless-stopped"
    environment:
      TYPE: "docker"
      BASE_URL: "https://localhost"
      DATABASE_HOST: "php-dynamic-qrcode-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "qrcode"
      DATABASE_USER: "qrcode"
      DATABASE_PASSWORD: "changeme"
      DATABASE_PREFIX: ""
      DATABASE_CHARSET: "utf8"
    ports:
      - "4867:80"  # Umbrel Apps verwenden interne Ports, setze hier 4867 fest für Umbrel-Kompatibilität
    depends_on:
      - php-dynamic-qrcode-db
    volumes:
      - php_dynamic_qrcode_saved_qrcode_data:/data/saved_qrcode  # Umbrel speichert Daten in /data
    networks:
      - php-dynamic-qrcode-network

  php-dynamic-qrcode-db:
    image: "giandonatoinverso/php-dynamic-qr-code-db:latest"
    restart: "unless-stopped"
    volumes:
      - php_dynamic_qrcode_db_data:/data/mysql  # Passe die Volumes für Umbrel an
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "qrcode"
      MYSQL_USER: "qrcode"
      MYSQL_PASSWORD: "changeme"
    networks:
      - php-dynamic-qrcode-network

  app_proxy:
    environment:
      # Der Hostname und der Port müssen für Umbrel spezifisch sein
      APP_HOST: php-dynamic-qrcode
      APP_PORT: 4867  # Gleicher Port wie oben im Hauptservice
    networks:
      - php-dynamic-qrcode-network

volumes:
  php_dynamic_qrcode_db_data:
  php_dynamic_qrcode_saved_qrcode_data:

networks:
  php-dynamic-qrcode-network:
    driver: bridge
