version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: qrcode_server_1
      APP_PORT: 4867

  server:
    image: "giandonatoinverso/php-dynamic-qr-code:latest"
    restart: unless-stopped
    user: "1000:1000"
    environment:
      TYPE: "docker"
      BASE_URL: "https://mydomain.com"
      DATABASE_HOST: "qrcode_db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "qrcode"
      DATABASE_USER: "qrcode"
      DATABASE_PASSWORD: "changeme"
      DATABASE_PREFIX: ""
      DATABASE_CHARSET: "utf8"
    volumes:
      - php_dynamic_qrcode_saved_qrcode_data:/data/saved_qrcode
    ports:
      - "4876:80"
    depends_on:
      - qrcode_db
    networks:
      - app_network

  qrcode_db:
    image: "giandonatoinverso/php-dynamic-qr-code-db:latest"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "qrcode"
      MYSQL_USER: "qrcode"
      MYSQL_PASSWORD: "changeme"
    volumes:
      - php_dynamic_qrcode_db_data:/data/mysql
    networks:
      - app_network

volumes:
  php_dynamic_qrcode_saved_qrcode_data:
  php_dynamic_qrcode_db_data:

networks:
  app_network:
    driver: bridge
